<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

?>

<div class="row">
    <div class="col-lg-6">
        <div class="card card-body">
            <h4 class="page-header mb-4"><i class="fas fa-list-ol"></i> <?= $this->getBreadcrumbBag()->getLastName(); ?> <small>(<?= count($answers); ?>)</small></h4>

            <form autocomplete="off">
                <?= $this->widget(new GridViewWidget($answers, [
                    'tableClass' => 'table table-hover table-bordered table-striped',
                    'rowAttributes' => [
                        'class' => function($row) use ($answer){
                            return $row->getId() == $answer->getId() ? 'table-info' : null;
                        }
                    ],

                    'columns' => [
                        [
                            'column' => 'id',
                            'label' => '#'
                        ],

                        [
                            'column' => 'answer'
                        ],

                        [
                            'column' => 'correct',
                            'translateable' => true,
                            'value' => function($entity){
                                return $entity->getCorrect() ? 'Yes' : 'No';
                            }
                        ],

                        [
                            'column' => 'order'
                        ]
                    ],

                    'actions' => [
                        function($row){
                            return Icon::edit(
                                $this->url('Quiz:Admin:Answer@editAction', $row['id']),
                                $this->translate('Edit this question')
                            );
                        },

                        function($row){
                            return Icon::remove(
                                $this->url('Quiz:Admin:Answer@deleteAction', $row['id']),
                                $this->translate('Remove this question')
                            );
                        }
                    ]
                ])); ?>
            </form>

            <?php if (empty($answers)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No answers'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card card-body">
            <h4 class="page-header mb-4"><i class="fas fa-pencil-alt"></i> <?= $this->translate(!$answer->getId() ? 'Add new answer' : 'Edit the answer'); ?></h4>

            <form autocomplete="off">
                <?= Element::hidden('answer[id]', $answer->getId()); ?>
                <?= Element::hidden('answer[question_id]', $answer->getQuestionId()); ?>

                <div class="mb-3">
                    <label class="form-label"><?= $this->translate('Answer'); ?></label>
                    <?= Element::textarea('answer[answer]', $answer->getAnswer(), ['class' => 'form-control', 'placeholder' => $this->translate('Type the answer')]); ?>
                </div>

                <div class="mb-3">
                    <label class="form-label"><?= $this->translate('Sort order'); ?></label>
                    <?= Element::text('answer[order]', $answer->getOrder(), ['class' => 'form-control', 'placeholder' => $this->translate('Sorting order. By default comes last')]); ?>
                </div>

                <div class="mb-3">
                    <label class="form-label"><?= $this->translate('Corectness'); ?></label>
                    <?= Element::select('answer[correct]', $this->translateArray([
                        '0' => 'This answer is incorreсt',
                        '1' => 'This answer is correсt'
                    ]), $answer->getCorrect(), ['class' => 'form-select']); ?>
                </div>

                <?php $this->loadPartial('actions', [
                    'new' => !$answer->getId(),
                    'add' => ['Quiz:Admin:Answer@listAction', $answer->getQuestionId()],
                    'edit' => 'Quiz:Admin:Answer@editAction',
                    'save' => 'Quiz:Admin:Answer@saveAction',
                    'cancel' => !$answer->getId() ? 'Quiz:Admin:Browser@indexAction' : ['Quiz:Admin:Answer@listAction', $answer->getQuestionId()]
                ]); ?>
            </form>
        </div>
    </div>
</div>