<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;
use Krystal\Form\HtmlHelper;

?>


<div class="btn-toolbar">
    <a href="<?php echo $this->url('Quiz:Admin:Answer@addAction', $id); ?>" class="btn btn-success"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></a>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
         <li class="divider"></li>
         <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
         
         <?php if(!empty($questions)): ?>
         <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Quiz:Admin:Answer@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Quiz:Admin:Answer@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         
         <?php else: ?>
         <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
         
         <?php endif; ?>
      </ul>
    </div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Answers')); ?>

<form>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th class="text-center">
                        <?php if (!empty($answers)): ?>
                        <input type="checkbox" />
                        <?php endif; ?>
                    </th>
                    <th class="text-center"><?php $this->show('#'); ?></th>
                    <th class="text-center"><?php $this->show('Answer'); ?></th>
                    <th class="text-center"><?php $this->show('Correct'); ?></th>
                    <th class="text-center"><?php $this->show('Order'); ?></th>
                    <th class="text-center"><?php $this->show('Actions'); ?></th>
                </tr>
            </thead>

            <?php if (!empty($answers)): ?>
            <tbody>
                <?php foreach ($answers as $answer): ?>
                <tr>
                    <td class="text-center">
                        <input type="checkbox" name="toDelete[<?php echo $answer->getId(); ?>]" />
                    </td>
                    <td class="text-center text-muted"><?php echo $answer->getId(); ?></td>
                    <td class="text-center"><?php echo $answer->getAnswer(); ?></td>
                    <td class="text-center"><?php echo $this->translate($answer->getCorrect() ? 'Yes' : 'No'); ?></td>
                    <td class="text-center col-lg-2">
                        <?php echo Element::number(sprintf('order[%s]', $answer->getId()), $answer->getOrder(), array('class' => 'form-control', 'min' => '0')); ?>
                    </td>
                    <td class="text-center">
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this question'); ?>" data-button="edit" href="<?php echo $this->url('Quiz:Admin:Answer@editAction', $answer->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this question'); ?>" data-button="delete" href="#" data-url="<?php echo $this->url('Quiz:Admin:Answer@deleteAction', $answer->getId()); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
            <?php endif; ?>
        </table>
        
        <?php if (empty($answers)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No answers'); ?></h2>
        </div>
        <?php endif; ?>
    </div>
</form>
