<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>
<form data-group="answer">
    <div class="well">
        <?php echo Element::hidden('answer[id]', $answer->getId()); ?>
        <?php echo Element::hidden('answer[question_id]', $answer->getQuestionId()); ?>

        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Answer'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::text('answer[answer]', $answer->getAnswer(), array('class' => 'form-control', 'placeholder' => $this->translate('Type the answer'))); ?>
            </div>
        </div>
        
        <div class="answer-form-group">
            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Sort order'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::text('answer[order]', $answer->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Sorting order. By default comes last'))); ?>
                </div>
            </div>
        </div>
        
        <div class="answer-form-group">
            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Corectness'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::select('answer[correct]', $this->translateArray(
                        array(
                            '0' => 'This answer is incorreсt',
                            '1' => 'This answer is correсt'
                        )), $answer->getCorrect(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>
    </div>

    <?php if (!$answer->getId()): ?>
    <button data-button="add" data-back-url="<?php echo $this->url('Quiz:Admin:Answer@editAction', null); ?>" data-url="<?php echo $this->url('Quiz:Admin:Answer@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" data-back-url="<?php echo $this->url('Quiz:Admin:Answer@addAction', $answer->getCategoryId()); ?>" data-url="<?php echo $this->url('Quiz:Admin:Answer@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
    
    <?php else: ?>
    <button data-button="save" data-url="<?php echo $this->url('Quiz:Admin:Answer@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-button="save-create" data-back-url="<?php echo $this->url('Quiz:Admin:Answer@addAction', $answer->getQuestionId()); ?>" data-url="<?php echo $this->url('Quiz:Admin:Answer@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

    <?php endif; ?>
    <button data-button="cancel" data-url="<?php echo $this->url('Quiz:Admin:Answer@listAction', $answer->getQuestionId()); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
