<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;
use Krystal\Form\HtmlHelper;

?>

<div class="btn-toolbar">
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
         <li><a href="<?php echo $this->url('Quiz:Admin:Question@addAction', $categoryId); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new question'); ?></a></li>
         <li><a href="<?php echo $this->url('Quiz:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
         <li><a href="<?php echo $this->url('Quiz:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add new category'); ?></a></li>
         <li><a href="<?php echo $this->url('Quiz:Admin:History@indexAction'); ?>"><i class="fa fa-history"></i> <?php $this->show('History'); ?></a></li>

         <li class="divider"></li>
         <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

         <?php if(!empty($questions)): ?>
         <?php if ($config->sortByOrder()): ?>
         <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Quiz:Admin:Question@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <?php endif; ?>
         <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Quiz:Admin:Question@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>

         <?php else: ?>
         <?php if ($config->sortByOrder()): ?>
         <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
         <?php endif; ?>
         <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>

         <?php endif; ?>
      </ul>
    </div>
    
    <a target="_blank" href="<?php echo $this->url('Quiz:Quiz@indexAction'); ?>" class="btn btn-info"><i class="fa fa-folder-open"></i> <?php $this->show('Open on site'); ?></a>
</div>


<form>
    <div class="row">
        <div class="col-lg-6">
            <?php $this->loadPartial('items-per-page', array('caption' => 'Questions')); ?>
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped table-condensed">
                    <thead>
                        <tr>
                            <th class="text-center">
                                <?php if (!empty($questions)): ?>
                                <input type="checkbox" />
                                <?php endif; ?>
                            </th>
                            <th class="text-center"><?php $this->show('#'); ?></th>
                            <th class="text-center"><?php $this->show('Question'); ?></th>

                            <?php if ($config->sortByOrder()): ?>
                            <th class="text-center"><?php $this->show('Order'); ?></th>
                            <?php endif; ?>

                            <th class="text-center"><?php $this->show('Actions'); ?></th>
                        </tr>
                    </thead>
                    
                    <?php if (!empty($questions)): ?>
                    <tbody>
                        <?php foreach ($questions as $question): ?>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="toDelete[<?php echo $question->getId(); ?>]" />
                            </td>
                            <td class="text-center text-muted"><?php echo $question->getId(); ?></td>
                            <td class="text-center"><?php echo $question->getQuestion(); ?></td>
                            <?php if ($config->sortByOrder()): ?>
                            <td class="text-center col-lg-2">
                                <?php echo Element::number(sprintf('order[%s]', $question->getId()), $question->getOrder(), array('class' => 'form-control', 'min' => '0')); ?>
                            </td>
                            <?php endif; ?>
                            <td class="text-center">
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View answers'); ?>" data-button="details" href="<?php echo $this->url('Quiz:Admin:Answer@listAction', $question->getId()); ?>"><i class="glyphicon glyphicon-fullscreen"></i></a>
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this question'); ?>" data-button="edit" href="<?php echo $this->url('Quiz:Admin:Question@editAction', $question->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this question'); ?>" data-button="delete" href="#" data-url="<?php echo $this->url('Quiz:Admin:Question@deleteAction', $question->getId()); ?>"><i class="glyphicon glyphicon-remove"></i></a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <?php endif; ?>
                </table>
                
                <?php if (empty($questions)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No questions'); ?></h2>
                </div>
                <?php endif; ?>
                
                <?php $this->loadPartial('paginator'); ?>
            </div>
        </div>
        
        <div class="col-lg-6">
            <div class="table-responsive">
                <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th class="text-center"><?php $this->show('#'); ?></th>
                                <th class="text-center"><?php $this->show('Name'); ?></th>
                                <th class="text-center"><?php $this->show('Amount of questions'); ?></th>
                                <th class="text-center"><?php $this->show('Sort order'); ?></th>
                                <th class="text-center"><?php $this->show('Actions'); ?></th>
                            </tr>
                        </thead>
                        
                        <?php if (!empty($categories)): ?>
                        <tbody>
                            <?php foreach ($categories as $category): ?>
                            <tr class="<?php echo HtmlHelper::addOnDemand(isset($categoryId) && $categoryId == $category->getId(), 'info'); ?>">
                                <td class="text-center text-muted"><?php echo $category->getId(); ?></td>
                                <td class="text-center">
                                    <a href="<?php echo $this->url('Quiz:Admin:Browser@categoryAction', $category->getId(), 1); ?>"><?php echo $category->getName(); ?></a>
                                </td>
                                <td class="text-center"><?php echo $category->getQuestionsCount(); ?></td>
                                <td class="text-center"><?php echo $category->getOrder(); ?></td>
                                <td class="text-center">
                                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this category'); ?>" data-button="edit" href="<?php echo $this->url('Quiz:Admin:Category@editAction', $category->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this category'); ?>" data-button="delete" data-url="<?php echo $this->url('Quiz:Admin:Category@deleteAction', $category->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <?php endif; ?>
                    </table>
                    
                    <?php if (empty($categories)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</form>
