<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

?>

<div class="btn-toolbar mb-3">
    <div class="btn-group me-2">
        <?php $this->loadPartial('menu', [
            'items' => [
                $this->url('Quiz:Admin:Question@addAction', $categoryId) => 'Add new question',
                'Quiz:Admin:Config@indexAction' => 'Configuration',
                'Quiz:Admin:Category@addAction' => 'Add new category',
                'Quiz:Admin:History@indexAction' => 'History'
            ],
            'actions' => [
                'data' => $questions,
                'save' => $config->sortByOrder() ? 'Quiz:Admin:Question@tweakAction' : null,
                'delete' => 'Quiz:Admin:Question@deleteAction'
            ]
        ]); ?>
    </div>

    <div class="btn-group me-2">
        <a target="_blank" href="<?= $this->url('Quiz:Quiz@indexAction'); ?>" class="btn btn-info"><i class="fas fa-folder-open"></i> <?= $this->translate('Open on site'); ?></a>
    </div>
</div>

<form>
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <?php $this->loadPartial('items-per-page', ['caption' => 'Questions']); ?>

                <div class="table-responsive">
                    <?= $this->widget(new GridViewWidget($questions, [
                        'batch' => true,
                        'pk' => 'id',
                        'tableClass' => 'table table-hover table-bordered table-striped table-sm',
                        'columns' => [
                            [
                                'column' => 'id',
                                'label' => '#'
                            ],

                            [
                                'column' => 'question',
                                'attributes' => [
                                    'class' => null
                                ]
                            ],

                            [
                                'column' => 'order',
                                'hidden' => !$config->sortByOrder(),
                                'value' => function($question){
                                    return Element::number(sprintf('order[%s]', $question->getId()), $question->getOrder(), ['class' => 'form-control', 'min' => '0']);
                                }
                            ]
                        ],

                        'actions' => [
                            function($question){
                                return Icon::details(
                                    $this->url('Quiz:Admin:Answer@listAction', $question->getId()),
                                    $this->translate('View answers')
                                );
                            },

                            function($question){
                                return Icon::edit(
                                    $this->url('Quiz:Admin:Question@editAction', $question->getId()),
                                    $this->translate('Edit this question')
                                );
                            },
                            function($question){
                                return Icon::remove(
                                    $this->url('Quiz:Admin:Question@deleteAction', $question->getId()),
                                    $this->translate('Remove this question')
                                );
                            }
                        ]
                    ])); ?>

                    <?php if (empty($questions)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No questions'); ?></h2>
                    </div>
                    <?php endif; ?>

                    <?php $this->loadPartial('paginator'); ?>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="card card-body">
                <h4 class="mb-3"><i class="fas fa-list"></i> <?= $this->translate('Categories'); ?> (<?= count($categories); ?>)</h4>

                <div class="table-responsive">
                    <?= $this->widget(new GridViewWidget($categories, [
                        'tableClass' => 'table table-hover table-bordered table-striped table-sm',
                        'rowAttributes' => [
                            'class' => function($category) use ($categoryId){
                                return $categoryId == $category->getId() ? 'table-info' : null;
                            }
                        ],

                        'columns' => [
                            [
                                'column' => 'id',
                                'label' => '#'
                            ],

                            [
                                'column' => 'name',
                                'attributes' => [
                                    'class' => null
                                ],
                                'value' => function($category){
                                    return Element::link($category->getName(), $this->url('Quiz:Admin:Browser@categoryAction', $category->getId(), 1));
                                }
                            ],

                            [
                                'column' => 'questions_count',
                                'label' => 'Amount of questions'
                            ],

                            [
                                'column' => 'order'
                            ]
                        ],

                        'actions' => [
                            function($category){
                                return Icon::edit(
                                    $this->url('Quiz:Admin:Category@editAction', $category->getId()),
                                    $this->translate('Edit this category')
                                );
                            },

                            function($category){
                                return Icon::remove(
                                    $this->url('Quiz:Admin:Category@deleteAction', $category->getId()),
                                    $this->translate('Remove this category')
                                );
                            }
                        ]
                    ])); ?>

                    <?php if (empty($categories)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No categories'); ?></h2>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</form>