<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="category" autocomplete="off">
    <?= Element::hidden('category[id]', $category->getId()); ?>

    <div class="form-group">
        <label><?php $this->show('Name'); ?></label>
        <?= Element::text('category[name]', $category->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Category name')]); ?>
    </div>

    <div class="form-group">
        <label><?php $this->show('Order'); ?></label>
        <?= Element::text('category[order]', $category->getOrder(), ['class' => 'form-control', 'placeholder' => $this->translate('Sorting order')]); ?>
    </div>

    <div class="form-group">
        <label><?php $this->show('Mark for right answer'); ?></label>
        <?= Element::text('category[mark]', $category->getMark(), ['class' => 'form-control']); ?>
    </div>

    <div class="form-group">
        <label><?php $this->show('Listing limit'); ?></label>
        <?= Element::text('category[limit]', $category->getLimit(), ['class' => 'form-control']); ?>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$category->getId(),
        'add' => 'Quiz:Admin:Category@addAction',
        'edit' => 'Quiz:Admin:Category@editAction',
        'save' => 'Quiz:Admin:Category@saveAction',
        'cancel' => 'Quiz:Admin:Browser@indexAction'
    ]); ?>
</form>