<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<form action="<?= $route; ?>" novalidate autocomplete="off">
    <div class="btn-toolbar mb-3">
        <?php if (!empty($records)): ?>
        <div class="btn-group me-2">
            <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i> <?= $this->translate('Filter'); ?></button>
        </div>
        <?php endif; ?>

        <?php if ($filterApplied): ?>
        <div class="btn-group me-2">
            <a href="<?= $this->url('Quiz:Admin:History@indexAction'); ?>" class="btn btn-primary"><i class="bi bi-trash"></i> <?= $this->translate('Reset filter'); ?></a>
        </div>
        <?php endif; ?>

        <div class="btn-group me-2">
            <a href="#" class="btn btn-danger" data-button="remove-selected" data-url="<?= $this->url('Quiz:Admin:History@deleteAction', null); ?>"><i class="bi bi-x-circle"></i> <?= $this->translate('Remove selected'); ?></a>
        </div>
    </div>

    <div class="card">
        <?php $this->loadPartial('items-per-page', ['caption' => 'History']); ?>

        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($records, [
                // A column to be considered as a primary key
                'pk' => 'id',
                'batch' => true,
                'tableClass' => 'table table-hover table-bordered table-striped table-sm',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'name',
                        'type' => 'text',
                        'filter' => true
                    ],

                    [
                        'column' => 'category',
                        'type' => 'select',
                        'filter' => $categories
                    ],

                    [
                        'column' => 'points',
                        'type' => 'text',
                        'filter' => true
                    ]
                ]

            ], $route)); ?>

            <?php if (empty($records)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No records'); ?></h2>
            </div>
            <?php endif; ?>
        </div>

        <?php $this->loadPartial('paginator'); ?>
    </div>
</form>