<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>
<form data-group="question">
    <div class="well">
        <?php echo Element::hidden('question[id]', $question->getId()); ?>
        
        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Question'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('question[question]', $question->getQuestion(), array('class' => 'form-control', 'placeholder' => $this->translate('Target question'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('question[category_id]', $categories, $question->getCategoryId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::number('question[order]', $question->getOrder(), array('min' => '0', 'class' => 'form-control', 'placeholder' => $this->translate('Order of this question to be displayed in a category'))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
    </div>
    
    <?php if (!$question->getId()): ?>
    <button data-button="add" data-back-url="<?php echo $this->url('Quiz:Admin:Question@editAction', null); ?>" data-url="<?php echo $this->url('Quiz:Admin:Question@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" data-back-url="<?php echo $this->url('Quiz:Admin:Question@addAction'); ?>" data-url="<?php echo $this->url('Quiz:Admin:Question@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
    
    <?php else: ?>
    <button data-button="save" data-url="<?php echo $this->url('Quiz:Admin:Question@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    
    <?php endif; ?>
    
    <button data-button="cancel" data-url="<?php echo $this->url('Quiz:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>
