<?php

use Krystal\Form\Element;

?>

<form class="card card-body" autocomplete="off">
    <?= Element::hidden('question[id]', $question->getId()); ?>

    <div class="row mb-3">
        <label class="col-lg-10 col-form-label"><?= $this->translate('Question'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('question[question]', $question->getQuestion(), ['class' => 'form-control', 'placeholder' => $this->translate('Target question')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-10 col-form-label"><?= $this->translate('Category'); ?></label>
        <div class="col-lg-10">
            <?= Element::select('question[category_id]', $categories, $question->getCategoryId(), ['class' => 'form-select']); ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-10 col-form-label"><?= $this->translate('Order'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::number('question[order]', $question->getOrder(), ['min' => '0', 'class' => 'form-control', 'placeholder' => $this->translate('Order of this question to be displayed in a category')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-10 col-form-label"><?= $this->translate('Description'); ?></label>
        <div class="col-lg-10">
            <?= Element::textarea('question[description]', $question->getDescription(), ['data-wysiwyg' => 'true']); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$question->getId(),
        'add' => ['Quiz:Admin:Question@addAction', $question->getCategoryId()],
        'edit' => 'Quiz:Admin:Answer@listAction',
        'save' => 'Quiz:Admin:Question@saveAction',
        'cancel' => 'Quiz:Admin:Browser@indexAction'
    ]); ?>

</form>