<?php

use Krystal\Form\Element;

?>

<p><?= $this->translate('Current category'); ?>: <?= $page->getCategoryName(); ?></p>

<form method="POST" action="<?= $this->url('Quiz:Quiz@indexAction'); ?>">
  <fieldset>
    <legend class="mb-3"><?= $question->getQuestion(); ?></legend>
    <?= Element::hidden('csrf-token', $csrfToken); ?>

    <p class="text-muted"><?= $this->translate('Question %s of %s', $currentQuestionCount, $initialCount); ?></p>

    <?php if ($question->getDescription()): ?>
    <div class="my-3">
        <?= $question->getDescription(); ?>
    </div>
    <?php endif; ?>

    <div class="row mb-3">
      <div class="col-lg-10">
        <input type="hidden" name="question" value="<?= $question->getId(); ?>" />

        <?php foreach ($answers as $answer): ?>
        <div class="form-check">
          <input type="<?= !$hasManyCorrectAnswers ? 'radio' : 'checkbox'; ?>" name="answerIds[]" id="<?= $answer->getSignature(); ?>" value="<?= $answer->getId(); ?>" class="form-check-input" />
          <label class="form-check-label" for="<?= $answer->getSignature(); ?>">
            <?= $answer->getAnswer(); ?>
          </label>
        </div>
        <?php endforeach; ?>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-lg-10">
        <a href="<?= $this->url('Quiz:Quiz@abortAction'); ?>" class="btn btn-danger"><?= $this->translate('Cancel'); ?></a>&nbsp;
        <?php if ($lastQuestion): ?>
        <button type="submit" class="btn btn-success"><?= $this->translate('Finish'); ?></button>
        <?php else: ?>

        <?php if (!$firstQuestion): ?>
        <a class="btn btn-secondary" href="<?= $this->url('Quiz:Quiz@indexAction', ['prev' => 1]); ?>"><?= $this->translate('Previous'); ?></a>
        <?php endif; ?>

        <button type="submit" class="btn btn-primary"><?= $this->translate('Next'); ?></button>
        <?php endif; ?>
      </div>
    </div>
  </fieldset>
</form>