<?php

use Krystal\Form\Element;

?>

<p><?php $this->show('Current category'); ?>: <?= $page->getCategoryName(); ?></p>

<form method="POST" action="<?= $this->url('Quiz:Quiz@indexAction'); ?>">
  <fieldset>
    <legend class="mb-3"><?= $question->getQuestion(); ?></legend>
    <?= Element::hidden('csrf-token', $csrfToken); ?>

    <p class="text-muted"><?= $this->translate('Question %s of %s', $currentQuestionCount, $initialCount); ?></p>

    <?php if ($question->getDescription()): ?>
    <div class="my-3">
        <?= $question->getDescription(); ?>
    </div>
    <?php endif; ?>

    <div class="row form-group">
      <div class="col-lg-10">
        <input type="hidden" name="question" value="<?= $question->getId(); ?>" />

        <?php foreach ($answers as $answer): ?>
        <div class="radio">
          <label for="<?= $answer->getSignature(); ?>">
            <input type="<?= !$hasManyCorrectAnswers ? 'radio' : 'checkbox'; ?>" name="answerIds[]" id="<?= $answer->getSignature(); ?>" value="<?= $answer->getId(); ?>" /><?= $answer->getAnswer(); ?>
          </label>
        </div>
        <?php endforeach; ?>
      </div>
    </div>

    <div class="row form-group mt-4">
      <div class="col-lg-10">
        <a href="<?= $this->url('Quiz:Quiz@abortAction'); ?>" class="btn btn-danger"><?php $this->show('Cancel'); ?></a>&nbsp;
        <?php if ($lastQuestion): ?>
        <button type="submit" class="btn btn-success"><?php $this->show('Finish'); ?></button>
        <?php else: ?>

        <?php if (!$firstQuestion): ?>
        <a class="btn btn-secondary" href="<?= $this->url('Quiz:Quiz@indexAction', ['prev' => 1]); ?>"><?php $this->show('Previous'); ?></a>
        <?php endif; ?>

        <button type="submit" class="btn btn-primary"><?php $this->show('Next'); ?></button>
        <?php endif; ?>
      </div>
    </div>
  </fieldset>
</form>