<?php

use Krystal\Form\Element;

?>

<form method="POST" action="<?= $this->url('Quiz:Quiz@indexAction'); ?>">
  <fieldset>
    <legend class="mb-4"><?php $this->show('Welcome to Quiz'); ?></legend>

    <?= Element::hidden('csrf-token', $csrfToken); ?>

    <div class="form-group mb-3">
      <label><?php $this->show('Name'); ?></label>
      <input class="form-control" name="name" placeholder="<?php $this->show('Type your name'); ?>" />
    </div>

    <div class="form-group mb-3">
      <label><?php $this->show('Category'); ?></label>
      <select class="form-control" name="category">
        <?php foreach ($categories as $id => $category): ?>
        <option value="<?php echo $id; ?>"><?php echo $category?></option>
        <?php endforeach; ?>
      </select>
    </div>

    <div class="form-group mb-3">
       <button type="submit" class="btn btn-primary"><?php $this->show('Start'); ?></button>
    </div>
  </fieldset>
</form>