<h2 class="page-header"></h2>

<form class="form-horizontal" method="POST">
  <fieldset>
    <legend><?php echo $question->getQuestion(); ?></legend>
    
    <p class="text-muted"><?php echo $this->translate('Question %s of %s', $currentQuestionCount, $initialCount)?></p>
    
    <div class="form-group">
      <div class="col-lg-10">
        
        <input type="hidden" name="question" value="<?php echo $question->getId(); ?>" />
        
        <?php foreach ($answers as $answer): ?>
        <div class="radio">
          <label for="<?php echo $answer->getSignature(); ?>">
            <input type="<?php echo !$hasManyCorrectAnswers ? 'radio' : 'checkbox'; ?>" name="answerIds[]" id="<?php echo $answer->getSignature(); ?>" value="<?php echo $answer->getId(); ?>" /><?php echo $answer->getAnswer(); ?>
          </label>
        </div>
        <?php endforeach; ?>
        
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10">
        <button type="reset" class="btn btn-default"><i class="glyphicon glyphicon-ban-circle"></i> <?php $this->show('Cancel'); ?></button>&nbsp;
        <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Next'); ?></button>
      </div>
    </div>
  </fieldset>
</form>