<?php

use Krystal\Form\Element;

?>

<form method="POST" action="<?= $this->url('Quiz:Quiz@indexAction'); ?>">
  <fieldset>
    <legend class="mb-4"><?= $this->translate('Welcome to Quiz'); ?></legend>

    <?= Element::hidden('csrf-token', $csrfToken); ?>

    <div class="mb-3">
      <label class="form-label"><?= $this->translate('Name'); ?></label>
      <input class="form-control" name="name" placeholder="<?= $this->translate('Type your name'); ?>" />
    </div>

    <div class="mb-3">
      <label class="form-label"><?= $this->translate('Category'); ?></label>
      <select class="form-select" name="category">
        <?php foreach ($categories as $id => $category): ?>
        <option value="<?= $id; ?>"><?= $category; ?></option>
        <?php endforeach; ?>
      </select>
    </div>

    <div class="mb-3">
       <button type="submit" class="btn btn-primary"><?= $this->translate('Start'); ?></button>
    </div>
  </fieldset>
</form>