<?php

use Krystal\Form\Element;

?>

<form class="form-horizontal" method="POST" action="<?php echo $this->url('Quiz:Quiz@indexAction'); ?>">
  <fieldset>
    <legend><?php echo $question->getQuestion(); ?></legend>
    <?= Element::hidden('csrf-token', $csrfToken); ?>

    <p class="text-muted"><?php echo $this->translate('Question %s of %s', $currentQuestionCount, $initialCount); ?></p>

    <article><?php echo $question->getDescription(); ?></article>

    <div class="form-group">
      <div class="col-lg-10">
        <input type="hidden" name="question" value="<?php echo $question->getId(); ?>" />

        <?php foreach ($answers as $answer): ?>
        <div class="radio">
          <label for="<?php echo $answer->getSignature(); ?>">
            <input type="<?php echo !$hasManyCorrectAnswers ? 'radio' : 'checkbox'; ?>" name="answerIds[]" id="<?php echo $answer->getSignature(); ?>" value="<?php echo $answer->getId(); ?>" /><?php echo $answer->getAnswer(); ?>
          </label>
        </div>
        <?php endforeach; ?>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10">
        <a href="<?php echo $this->url('Quiz:Quiz@abortAction'); ?>" class="btn btn-danger"><i class="glyphicon glyphicon-ban-circle"></i> <?php $this->show('Cancel'); ?></a>&nbsp;
        <?php if ($lastQuestion): ?>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> <?php $this->show('Finish'); ?></button>
        <?php else: ?>
        <button type="submit" class="btn btn-primary"><?php $this->show('Next'); ?> <i class="glyphicon glyphicon-chevron-right"></i></button>
        <?php endif; ?>
      </div>
    </div>
  </fieldset>
</form>