
<form class="form-horizontal" method="POST" action="<?php echo $this->url('Site:Quiz:Quiz@indexAction'); ?>">
  <fieldset>
    
    <legend>Welcome to Quiz</legend>
    
    <div class="form-group">
      <label for="inputName" class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" name="name" id="inputName" placeholder="<?php $this->show('Type your name'); ?>" />
      </div>
    </div>
    
    <div class="form-group">
      <label for="inputCategory" class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
      <div class="col-lg-10">
        <select class="form-control" name="category" id="inputCategory">
          <?php foreach ($categories as $id => $category): ?>
          <option value="<?php echo $id; ?>"><?php echo $category?></option>
          <?php endforeach; ?>
        </select>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary"><?php $this->show('Start'); ?> <i class="glyphicon glyphicon-chevron-right"></i></button>
      </div>
    </div>
    
  </fieldset>
</form>
